project:
  type: website

website:
  title: "advent_of_code"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - '2022.qmd'
      - '2022-python.qmd'

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



