project:
  type: website

website:
  title: "advent_of_code"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - '2022-r-lang.qmd'
      - '2022-python.qmd'

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-link: true



